--MERGE INTO temp_table1 T
--USING ( SELECT 1 ID, 'SomeDefaultObject' NAME, CURRENT_TIMESTAMP() CREATED_DATE FROM DUAL) D
--ON (T.ID = D.ID)
--WHEN MATCHED THEN
-- UPDATE SET T.NAME = D.NAME
--WHEN NOT MATCHED THEN
 --INSERT (NAME,CREATED_DATE) VALUES (D.NAME, D.CREATED_DATE);

--more simple merge syntax
--MERGE INTO temp_table1 (ID,NAME,CREATED_DATE)
 --KEY(ID) --can't be used due to: 'GENERATED ALWAYS AS IDENTITY' - can't be changed using VALUES.
 --VALUES (2,'Name2', CURRENT_TIMESTAMP());

-- select CAST(CREATED_DATE_TIME as DATE) as DT, count(1) from TEMP_TABLE1
 --group by DT;
